# Generated by Django 4.2.2 on 2023-07-01 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialPlusApp', '0002_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
